controller_manager:
  ros__parameters:
    update_rate: 50  # Control loop frequency in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController
      ros__parameters:
        # Controller behavior
        use_stamped_velocities: false    # Accepts unstamped velocity commands (from /cmd_vel)
        enable_odom_tf: true             # Publishes odometry transform (odom -> base_link)
        publish_rate: 50                 # Odometry publish rate in Hz

        # Robot kinematics
        left_wheel_names: ["left_wheel_joint"]
        right_wheel_names: ["right_wheel_joint"]
        wheel_separation: 0.5            # Distance between left and right wheels (meters)
        wheel_radius: 0.1                # Radius of each wheel (meters)

        # Velocity limits (adjust based on robot specs)
        linear.x.max_velocity: 1.0       # Max forward velocity (m/s)
        linear.x.min_velocity: -1.0      # Max backward velocity (m/s)
        linear.x.max_acceleration: 0.5   # Max forward/backward acceleration (m/s²)
        linear.x.min_acceleration: -0.5  # Max deceleration (m/s²)

        angular.z.max_velocity: 1.0      # Max rotational velocity (rad/s)
        angular.z.min_velocity: -1.0     # Max rotational velocity in reverse (rad/s)
        angular.z.max_acceleration: 0.5  # Max rotational acceleration (rad/s²)
        angular.z.min_acceleration: -0.5 # Max rotational deceleration (rad/s²)

        # Command timeout
        cmd_vel_timeout: 0.5             # Stop the robot if no command is received in 0.5 seconds
